version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: commander
    versions:
    - 6.2.1
    - 7.0.0
  - dependency-name: ora
    versions:
    - 5.2.0
  - dependency-name: simple-git
    versions:
    - 2.31.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: inquirer
    versions:
    - 7.3.3
